"""常量定义：集中管理系统用到的关键字符串、默认值与状态码。"""

from fastapi import status

DEFAULT_USER_ROLE = "user"
ADMIN_ROLE = "admin"
ACCESS_TOKEN_TYPE = "bearer"
DEFAULT_ORGANIZATION_NAME = "研发部"
DEFAULT_ADMIN_USERNAME = "admin"
DEFAULT_ADMIN_PASSWORD = "admin123"

# HTTP 状态码统一出口，避免在业务代码中散落“魔法数字”。
HTTP_STATUS_OK = status.HTTP_200_OK
HTTP_STATUS_CREATED = status.HTTP_201_CREATED
HTTP_STATUS_BAD_REQUEST = status.HTTP_400_BAD_REQUEST
HTTP_STATUS_UNAUTHORIZED = status.HTTP_401_UNAUTHORIZED
HTTP_STATUS_FORBIDDEN = status.HTTP_403_FORBIDDEN
HTTP_STATUS_NOT_FOUND = status.HTTP_404_NOT_FOUND
HTTP_STATUS_CONFLICT = status.HTTP_409_CONFLICT
HTTP_STATUS_UNPROCESSABLE_ENTITY = status.HTTP_422_UNPROCESSABLE_ENTITY
